// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DeletePostResponse struct {
	DeletePostID string `json:"deletePostId"`
}

type Mutation struct {
}

type NewPost struct {
	Title       string     `json:"Title"`
	Content     string     `json:"Content"`
	Author      *string    `json:"Author,omitempty"`
	Hero        *string    `json:"Hero,omitempty"`
	PublishedAt *time.Time `json:"Published_At,omitempty"`
	UpdatedAt   *time.Time `json:"Updated_At,omitempty"`
}

type Post struct {
	ID          string    `json:"_id"`
	Title       string    `json:"Title"`
	Content     string    `json:"Content"`
	Author      string    `json:"Author"`
	Hero        string    `json:"Hero"`
	PublishedAt time.Time `json:"Published_At"`
	UpdatedAt   time.Time `json:"Updated_At"`
}

type Query struct {
}
